FROM golang:1.23-alpine
WORKDIR /app
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@v1.52.3
RUN go install github.com/a-h/templ/cmd/templ@v0.2.747
COPY go.mod go.sum ./
RUN go mod download
CMD ["air", "-c", ".air.toml"]
